### PR TITLE
Quick spike for the new Coway authentication

### PR DESCRIPTION
**Pull request by ohmantics**
This gets us updated tokens for the new Coway authentication.

Matthew-- your fork seemed like the best modernized place to start on these changes. However, I don't use Typescript/JS/Node for a living, so I'm guessing my way through this. This fails when it first tries to use TokenStore, claiming `TypeError: this._serialize is not a function`. Due to the nature of store having plugins, it's a mess of deep JS stuff I've never needed nor want to know. :-)

(To my eye, TokenStore looks like an unnecessary abstraction anyway. Can Homebridge plugins ever run in any other context than would result in memoryStore, which is just using a global object?)

Can you suggest next steps toward finishing this?

### CODE REVIEW

**Comment by ohmantics** [comment]
With the last set of changes, everything appears to work fully. I'm going to keep running this for a few days for additional bake time and give others time to chime in on these changes. If nobody else speaks up, then I'll make more changes and publish yet another fork.

**Comment by chrisvanhorn** [comment]
> With the last set of changes, everything appears to work fully. I'm going to keep running this for a few days for additional bake time and give others time to chime in on these changes. If nobody else speaks up, then I'll make more changes and publish yet another fork.

You have no idea how happy my wife is going to be once these things work in our HomeKit home again. Thank you so much for your work on this!

**Comment by ohmantics** [comment]
Abandoning this pull request. I've published my changes on npm as version 3.3.0 as @ohmantics/homebridge-airmega.

**Comment by mroth** [comment]
I'm only now seeing this, but thank you @ohmantics for taking the charge on this!  I will likely archive this repository and point people at yours moving forward.

**Comment by ohmantics** [comment]
Sorry we weren't able to connect. Many thanks for all of your work. As I haven't really done much Node/JS/TS before, I'd love any feedback you have time for.

**Comment by mroth** [comment]
I actually have very little experience with Node/JS/TS as well I'm afraid.  My background is much more in systems programming with Go, Rust, etc.

**Comment by sugarfunk** [comment]
@ohmantics installed your version and everything is working! Thanks

**Pull request closed without merging**
